# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = tcp_service
DESTDIR = ../Debug
CONFIG += staticlib debug
DEFINES += TCP_SERVICE_LIB BUILD_STATIC
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(../tcp_service.pri)
