# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../source/socket/include/tcp_socket.h \
    ../source/socket/include/tcp_untlity.h \
    ../source/socket/include/tcp_thread_pool.h \
    ../source/socket/include/tcp_thread.h \
    ../source/socket/include/tcp_session.h \
    ../source/socket/include/tcp_server_service.h \
    ../source/socket/include/tcp_server.h \
    ../source/socket/include/tcp_listen.h \
    ../source/socket/include/event_arch.h \
    ../source/socket/include/event_config.h \
    ../source/socket/include/event_libqt.h \
    ../source/socket/include/event_platform.h \
    ../source/socket/include/event_stdint.h \
    ../source/socket/include/event_untlity.h
